### ISSUE TITLE
Update IntelliJ Plugin and Repository

### ISSUE THREAD

**Issue by lorriborri** [mercedes-benz/sechub-plugin-intellij#112]
# Wanted
1. plugin should be compatible with newest version of IDE
2. plugin must be importable (current way with https://plugins.jetbrains.com/plugins/alpha/list does not work anymore)

# Solution 
Make plugin compatible with IDE
Update custom repository (see: https://plugins.jetbrains.com/docs/intellij/custom-plugin-repository.html)
Update User guide (https://www.jetbrains.com/help/idea/managing-plugins.html#repos)

**Comment by de-jcup** [comment]
A custom plugin repository is only necessary when we do not use the official JetBrains marketplace, but we want to use it.

That the aplpha list channel is no longer available is a problem and must be solved.

**Comment by de-jcup** [comment]
I will close this issue - the upload of V0.4.0 has been done.
