### ISSUE TITLE
Handle deprecated method IconLoader.findIcon

### ISSUE THREAD

**Issue by company-jcup** [mercedes-benz/sechub-plugin-intellij#44]
## Situation
`IconLoader.findIcon(String)` has been marked as deprecated and must be replaced

see https://plugins.jetbrains.com/plugin/15424-sechub/versions/alpha/136692#verification-results

**Comment by de-jcup** [comment]
Hm.. the problem seems to be more serious.

A user has tested with PyCharm and Ultimate edition: the api is not only deprecated, but the installation of the plugin does no longer work at all - not clear if this because Icon loader (there is another deprecation) but this must be fixed soon.

**Comment by de-jcup** [comment]
This is done with commit 110f2dc
